#!/bin/bash
#
# update-semgrep-rules.sh — Manage community Semgrep rule sources
#
# Clones, updates, and verifies the community rule repositories used by
# the security-auditor agent's deep audit tier. Supports pinning via a
# .semgrep/community-rules.lock file in the project.
#
# Usage:
#   ./update-semgrep-rules.sh                    Clone any missing sources
#   ./update-semgrep-rules.sh --verify           Verify all sources match pinned commits
#   ./update-semgrep-rules.sh --bump             Pull latest, update lock file
#   ./update-semgrep-rules.sh --check-staleness  Warn on sources stale > 90 days
#   ./update-semgrep-rules.sh --help             Show this help
#
# Portable: works on macOS bash 3.2+ and Linux bash 4+.
#

set -euo pipefail

CACHE_DIR="${SEMGREP_COMMUNITY_CACHE:-$HOME/.cache/semgrep-community}"
LOCK_FILE="${PWD}/.semgrep/community-rules.lock"

# Community rule sources — parallel arrays (portable to bash 3.2)
# Keep in sync with references/semgrep-community-rules.md
SOURCE_NAMES=(trailofbits elttam gitlab 0xdea)
SOURCE_REPOS=(
  "https://github.com/trailofbits/semgrep-rules"
  "https://github.com/elttam/semgrep-rules"
  "https://gitlab.com/gitlab-org/security-products/sast-rules"
  "https://github.com/0xdea/semgrep-rules"
)

MODE="clone"
for arg in "$@"; do
  case $arg in
    --verify)           MODE="verify" ;;
    --bump)             MODE="bump" ;;
    --check-staleness)  MODE="staleness" ;;
    --help|-h)
      sed -n '3,15p' "$0" | sed 's/^# //'
      exit 0
      ;;
  esac
done

mkdir -p "$CACHE_DIR"

log()  { echo "  $*"; }
warn() { echo "⚠️  $*" >&2; }
ok()   { echo "✓  $*"; }
err()  { echo "❌ $*" >&2; }

# ── Mode: clone (default — clone missing sources) ──────────────────────
if [ "$MODE" = "clone" ]; then
  echo ""
  echo "Cloning missing community Semgrep rule sources to $CACHE_DIR"
  echo ""
  i=0
  for name in "${SOURCE_NAMES[@]}"; do
    repo="${SOURCE_REPOS[$i]}"
    target="$CACHE_DIR/$name"
    if [ -d "$target/.git" ]; then
      log "$name already cloned (skipping). Use --bump to pull latest."
    else
      log "Cloning $name from $repo..."
      git clone --depth 1 "$repo" "$target" 2>&1 | tail -3 || { err "Failed to clone $name"; i=$((i+1)); continue; }
      ok "$name ready at $target"
    fi
    i=$((i+1))
  done
  echo ""
  ok "Done. Community rules ready for deep audit."
  exit 0
fi

# ── Mode: verify (check sources match pinned commits) ──────────────────
if [ "$MODE" = "verify" ]; then
  echo ""
  echo "Verifying community rules against pinned commits..."
  echo ""
  if [ ! -f "$LOCK_FILE" ]; then
    warn "No $LOCK_FILE found — nothing to verify."
    echo "   Run with --bump to create a lock file from current state."
    exit 1
  fi

  fail=0
  for name in "${SOURCE_NAMES[@]}"; do
    target="$CACHE_DIR/$name"
    if [ ! -d "$target/.git" ]; then
      err "$name not cloned. Run without flags to clone."
      fail=1
      continue
    fi

    # Parse simple YAML — find the block for this name, extract commit line
    pinned=$(awk -v n="$name" '
      $0 ~ "^  "n":" { in_block=1; next }
      in_block && $0 ~ "^  [a-z0-9]" && $0 !~ "^  "n":" { in_block=0 }
      in_block && $1 == "commit:" { print $2; exit }
    ' "$LOCK_FILE")

    current=$(git -C "$target" rev-parse HEAD 2>/dev/null)

    if [ -z "$pinned" ]; then
      warn "$name: no pinned commit in lock file"
      continue
    fi

    if [ "$pinned" = "$current" ]; then
      ok "$name: $current (matches pin)"
    else
      err "$name: current=$current, pinned=$pinned"
      echo "     Run --bump to update lock, or 'git -C $target checkout $pinned' to match pin"
      fail=1
    fi
  done

  echo ""
  [ $fail -eq 0 ] && { ok "All sources verified."; exit 0; }
  exit 1
fi

# ── Mode: bump (pull latest, update lock file) ─────────────────────────
if [ "$MODE" = "bump" ]; then
  echo ""
  echo "Pulling latest community rules and updating $LOCK_FILE..."
  echo ""
  mkdir -p "$(dirname "$LOCK_FILE")"

  today=$(date '+%Y-%m-%d')
  {
    echo "# Semgrep community rule pinning"
    echo "# Last bumped: $today"
    echo "# Generated by scripts/update-semgrep-rules.sh --bump"
    echo ""
    echo "sources:"
  } > "$LOCK_FILE.new"

  i=0
  for name in "${SOURCE_NAMES[@]}"; do
    repo="${SOURCE_REPOS[$i]}"
    target="$CACHE_DIR/$name"

    if [ ! -d "$target/.git" ]; then
      log "$name not cloned yet — cloning..."
      git clone --depth 1 "$repo" "$target" 2>&1 | tail -2 || { err "Failed to clone $name"; i=$((i+1)); continue; }
    else
      log "Pulling latest for $name..."
      git -C "$target" fetch --depth 1 origin 2>&1 | tail -2 || { err "Fetch failed for $name"; i=$((i+1)); continue; }
      git -C "$target" reset --hard origin/HEAD 2>&1 | tail -2 || { err "Reset failed for $name"; i=$((i+1)); continue; }
    fi

    commit=$(git -C "$target" rev-parse HEAD)
    last_upstream=$(git -C "$target" log -1 --format=%cd --date=short HEAD)

    {
      echo "  $name:"
      echo "    repo: $repo"
      echo "    commit: $commit"
      echo "    pinned_at: $today"
      echo "    upstream_last_commit: $last_upstream"
    } >> "$LOCK_FILE.new"

    ok "$name: $commit (upstream $last_upstream)"
    i=$((i+1))
  done

  mv "$LOCK_FILE.new" "$LOCK_FILE"
  echo ""
  ok "Lock file updated: $LOCK_FILE"
  echo ""
  echo "Next step: run a full /security audit and compare finding count"
  echo "against the prior audit. Triage any new findings in docs/security/TRIAGE.md."
  exit 0
fi

# ── Mode: check-staleness ──────────────────────────────────────────────
if [ "$MODE" = "staleness" ]; then
  echo ""
  echo "Checking staleness of community rule sources..."
  echo "  WARN threshold:  90 days since upstream commit"
  echo "  FAIL threshold:  180 days since upstream commit"
  echo ""

  fail=0
  for name in "${SOURCE_NAMES[@]}"; do
    target="$CACHE_DIR/$name"
    if [ ! -d "$target/.git" ]; then
      warn "$name not cloned — skipping"
      continue
    fi

    git -C "$target" fetch --depth 1 origin 2>/dev/null || { warn "$name: fetch failed"; continue; }

    last_commit_epoch=$(git -C "$target" log -1 --format=%ct origin/HEAD 2>/dev/null || echo 0)
    now_epoch=$(date +%s)
    days_stale=$(( (now_epoch - last_commit_epoch) / 86400 ))
    last_date=$(git -C "$target" log -1 --format=%cd --date=short origin/HEAD 2>/dev/null)

    if [ "$days_stale" -gt 180 ]; then
      err "$name: $days_stale days stale (last commit $last_date) — ABANDONED? Consider removing."
      fail=1
    elif [ "$days_stale" -gt 90 ]; then
      warn "$name: $days_stale days stale (last commit $last_date) — consider bumping soon"
    else
      ok "$name: $days_stale days since last upstream commit ($last_date)"
    fi
  done

  echo ""
  [ $fail -eq 0 ] && { ok "No sources past FAIL threshold."; exit 0; }
  err "Some sources past FAIL threshold."
  exit 1
fi
